[metadata]
name = pydmart
version = 2.5.0
author = <Kefah Issa>
author_email = kefah.issa@gmail.com 
description = A client to connect to a Dmart instance
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/edraj/pydmart
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
    Operating System :: OS Independent
license_files = LICENSE.txt

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.11
install_requires =
    aiohttp>=3.14.3
    pydantic>=2.13.4

[options.packages.find]
where = src
